.decl uses(lmod:symbol, lname:symbol, umod:symbol, uname:symbol)
.input uses

.decl exported(lmod:symbol, lname:symbol, line:number, col:number)
.input exported

.decl defined(lmod:symbol, lname:symbol, line:number, col:number)
.input defined

.decl graph(lmod:symbol, lname:symbol, umod:symbol, uname:symbol)

graph(lmod, lname, umod, uname) :- uses(lmod, lname, umod, uname).
graph(lmod, lname, umod, uname) :- 
  graph(lmod, lname, a, b), 
  uses(a, b, umod, uname).
